RealTimeChatApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('chat.urls')),    
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_account, name='signup'),
]

chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'

urlpatterns = [
    path('', views.top, name='top'),
    path('chat/', views.index, name='index'),
    path('chat/<slug:room_name>/', views.room, name='room'),
]

accounts/models.py
from django.db import models

# Create your models here.

chat/models.py
from django.db import models
from django.contrib.auth.models import User


class UserCustomized(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError,ObjectDoesNotExist
import re

class RegistationForm(forms.Form):
    username = forms.CharField(max_length=30,widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Username',

        }
    ))
    email = forms.EmailField(required=True,widget=forms.EmailInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Email',

        }
    ))
    first_name = forms.CharField(max_length=30,widget=forms.TextInput(
        attrs={
            'class':'form-control',
            'placeholder':'First name',

        }
    ))
    last_name = forms.CharField(max_length=30, widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Last name',

        }
    ))
    password1 = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Password',

        }
    ))
    password2 = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Confirm password',

        }
    ))

    #check password confirm equal password
    def clean_password2(self):
        if 'password1' in self.data:
            password1 = self.cleaned_data.get('password1')
            password2 = self.cleaned_data.get('password2')
            if password1 and password2 and password1 ==password2:
                return password2
        raise ValidationError('Password does not match the confirm password.')

    #check if username  existed
    def clean_username(self):
        if 'username' in self.data:
            username = self.cleaned_data.get('username')
            if not re.search(r'^\w+$',username):
                raise ValidationError('Username can not contain special characters.')
            try:
                User.objects.get(username=username)
            except ObjectDoesNotExist:
                return username
            raise ValidationError('Username have already existed.')

    #create user
    def save(self):
        User.objects.create_user(self.cleaned_data['username'],
                                 self.cleaned_data['email'],
                                 self.cleaned_data['password1'],
                                 first_name=self.cleaned_data['first_name'],
                                 last_name=self.cleaned_data['last_name'])


class LoginForm(forms.Form):
    username = forms.CharField(max_length=30, widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Username',
            'name': 'username',
        }
    ))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Password',
            'name': 'password',

        }
    ))

accounts/views.py
from django.shortcuts import render, redirect
from .forms import RegistationForm

def signup_account(request):
    form = RegistationForm()
    if request.method == 'POST':
        form = RegistationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('chat:index')
    return render(request, 'signup.html', {'form': form})

chat/views.py
from django.shortcuts import render
from django.utils.safestring import mark_safe
import json


def top(request):
    return render(request, 'chat/top.html')


def index(request):
    return render(request, 'chat/index.html')


def room(request, room_name):
    return render(request, 'chat/room.html', {
        'room_name_json': mark_safe(json.dumps(room_name))
    })

accounts/templates/sign_up.html
{% load widget_tweaks %}



{% block title %}Sign up{% endblock %}

{% block content %}
<h1>Sign up</h1>
<section class="common-form">

    {% comment %} <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="submit">Sign up</button>
    </form> {% endcomment %}

    <form method="post">
        {% csrf_token %}
        {% for field in form.visible_fields %}
            {% if form.is_bound %}
                {% if field.errors %}
                    {% render_field field class="form-control is-invalid" %}
                    {% for error in field.errors %}
                        {{ error }}
                    {% endfor %}
                {% else %}
                    {% render_field field class="form-control is-valid" %}
                {% endif %}
            {% else %}
                {% render_field field class="form-control" %}
            {% endif %}
            <br>
        {% endfor %}
        <button type="submit">Sign up</button>
    </form>

</section>
{% endblock %}

accounts/templates/signup.html
{% load widget_tweaks %}


{% load static %}


{% block content %}
<head>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
</head>

<section class="common-form">

    <div class="container">
        <div class="row form-signup">
            <div class="col-md-4"></div>
            <div class="col-md-4">
                <h3>Sign up</h3>
                <form method="post">
                    {% csrf_token %}
                    {% for field in form.visible_fields %}
                        <div class="form-group">
                            {% if form.is_bound %}
                                {% if field.errors %}
                                    {% render_field field class="form-control is-invalid" %}
                                    {% for error in field.errors %}
                                        <div class="invalid-feedback">
                                            {{ error }}
                                        </div>
                                    {% endfor %}
                                {% else %}
                                    {% render_field field class="form-control is-valid" %}
                                {% endif %}
                            {% else %}
                                {% render_field field class="form-control" %}
                            {% endif %}
                        </div>
                    {% endfor %}
                    <button type="submit" class="btn btn-primary btn-submit btn-block">Sign up</button>
                </form>
            </div>
            <div class="col-md-4"></div>
        </div>
    </div>

</section>
{% endblock %}

chat/templates/chat/base.html
{% load staticfiles %}


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <title>Chat App</title>
</head>

<body>
    <div class="col-xs-3">
        <h4> guest </h4>
    </div>

    <div class="content">
        {% block content %}{% endblock %}
    </div>
</body>

chat/templates/chat/index.html
{% extends 'base.html' %}
{% load static %}



{% block content %}
    <p class="test-css">What chat room would you like to enter?</p>
    <input id="room-name-input" type="text" size="100"/><br/>
    <input id="room-name-submit" type="button" value="Enter"/>
    

<script>
    document.querySelector('#room-name-input').focus();
    document.querySelector('#room-name-input').onkeyup = function(e) {
        if (e.keyCode === 13) {  // enter, return
            document.querySelector('#room-name-submit').click();
        }
    };
    document.querySelector('#room-name-submit').onclick = function(e) {
        var roomName = document.querySelector('#room-name-input').value;
        window.location.pathname = '/chat/' + roomName + '/';
    };
</script>
{% endblock %}

chat/templates/chat/room.html
{% extends 'base.html' %}
{% load static %}


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Room</title>
    <link rel="stylesheet" href="{% static 'chat/css/room.css' %}">
</head>


{% block content %}

    <div class="row">
        <div class="col-sm-12">
            <div id="chat-log" class="chat-message">
            </div>
            <footer class="fixed-bottom text-right mx-4" style="bottom: 100px; right: 100px">
                <input id="chat-message-input" class="input" type="text" size="100"/>
                <input id="chat-message-submit" type="button" value="Send"/>
            </footer>
        </div>
    </div>
        

<script>
    var roomName = {{ room_name_json }};
    var chatSocket = new WebSocket(
        'ws://' + window.location.host +
        '/ws/chat/' + roomName + '/');
    chatSocket.onmessage = function(e) {
        var data = JSON.parse(e.data);
        var message = data['message'];
        var info = document.getElementById('chat-log');
        var pNode = document.createElement('p');
        var textNode = document.createTextNode(message);
        pNode.appendChild(textNode);
        info.appendChild(pNode);
    };
    chatSocket.onclose = function(e) {
        console.error('Chat socket closed unexpectedly');
    };
    document.querySelector('#chat-message-input').focus();
    // document.querySelector('#chat-message-input').onkeyup = function(e) {
    //     if (e.keyCode === 13) {  // enter, return
    //         document.querySelector('#chat-message-submit').click();
    //     }
    // };
    document.querySelector('#chat-message-submit').onclick = function(e) {
        var messageInputDom = document.querySelector('#chat-message-input');
        var message = messageInputDom.value;
        chatSocket.send(JSON.stringify({
            'message': message
        }));
        messageInputDom.value = '';
    };
</script>
{% endblock %}
</html>

chat/templates/chat/top.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<head>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
</head>

<section class="common-form">

    <div class="container">
        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-4">
                <h3>Top Page</h3>
                <a href="/accounts/signup/">Sign Up</a>
                <br>
                <a href="/accounts/login/">Login</a>
            </div>
            <div class="col-md-4"></div>
        </div>
    </div>

</section>
{% endblock %}

templates/base.html
{% load staticfiles %}


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'chat/css/base.css' %}">
    <title>Chat App</title>
</head>
<body>
    <div class="container-fluid wrapper">
        <div class="row inner-wrapper">
            <div class="col-sm-3 menu">
                    {% if user.is_authenticated %}
                    <h3 class="text-center mt-4">{{ user }}</h3>
                   {% else %}
                   <h3 class="text-center mt-4"> guest </h3>
                   {% endif %}

                   <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
            </div>

            <div class="col-sm-9">
                <h1> Real Time Chat App</h1>
                {% if user.is_authenticated %}
                <div class="float-right">
                    <a href="{% url 'logout' %}" class="logout btn btn-danger flex-lg-last" role="button">Logout</a>   
                </div>
                {% else %}
                <div class="float-right ">
                    <a href="{% url 'accounts:signup' %}" class="btn btn-primary flex-lg-last" role="button">Sign up</a>
                    <a href="{% url 'login' %}" class="btn btn-success flex-lg-last" role="button">Login</a>
                </div>
                {% endif %}
                <br/>
                <hr color="black" width="90%"/>
                <div class="row">
                    <div class="col-sm-12">
                            {% block content %}{% endblock %}
                    </div>
                </div>
            </div>
        </div>
    </div>
        <!-- <div class="menu">
            {% if user.is_authenticated %}
             <h3 class="text-center mt-4">{{ user }}</h3>
            {% else %}
            <h3> guest </h3>
            {% endif %}
        </div>
         -->
</body>
</html>